name: bash
on: [push]
jobs:

  build:
    name: Pull and Release
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        env: 
          LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
        run: |
          wget -O ./GeoLite2-City.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${LICENSE_KEY}&suffix=tar.gz"
          tar zxvf ./GeoLite2-City.tar.gz -C .
          mv ./GeoLite2-City_*/GeoLite2-City.mmdb ./City.mmdb
          wget -O ./GeoLite2-ASN.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${LICENSE_KEY}&suffix=tar.gz"
          tar zxvf ./GeoLite2-ASN.tar.gz -C .
          mv ./GeoLite2-ASN_*/GeoLite2-ASN.mmdb ./ASN.mmdb
          wget -O ./GeoLite2-Country.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${LICENSE_KEY}&suffix=tar.gz"
          tar zxvf ./GeoLite2-Country.tar.gz -C .
          mv ./GeoLite2-Country_*/GeoLite2-Country.mmdb ./Country.mmdb

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            City.mmdb
            ASN.mmdb
            Country.mmdb
